services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  queue_setup:
    build: .
    command: python queue_setup.py
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password
      - START_SELLER_ID=1
      - END_SELLER_ID=30000
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: "no"

  parser:
    build: .
    command: python parser.py
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./screenshots:/app/screenshots
      - ./html:/app/html
    depends_on:
      queue_setup:
        condition: service_completed_successfully
    restart: unless-stopped

volumes:
  rabbitmq_data: