services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASS}
    ports:
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 10s
      retries: 5

  queue_setup:
    build: .
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - TOTAL_SELLERS=10
    command: python queue_setup.py
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: on-failure

  parser:
    build: .
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=${RABBITMQ_PASS}
      - USE_PROXIES=false
    deploy:
      resources:
        limits:
          memory: 800M
    depends_on:
      rabbitmq:
        condition: service_healthy
    restart: unless-stopped
    # Увеличим лимиты CPU при необходимости
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '1.0'
    #       memory: 1G

volumes:
  rabbitmq_data: